service: python-wordcloud-layers
frameworkVersion: ">=1.34.0 <2.0.0"

custom:
  default_stage: dev
  stage: ${opt:stage, self:custom.default_stage}
  region: us-east-1

provider:
  name: aws
  stage: ${opt:stage, 'dev'}
  region: us-east-1

layers:
  wordCloudPython36_1:
    path: layer
    description: A Layer to support wordcloud in Python 3.6 Lambda functions contains wordcloud, pdfminer and matplotlib
    compatibleRuntimes:
      - python3.6
